[Variables]
TotalGame=29

Gamecover8=GTAV.png
Gamedir8=C:\Program Files (x86)\Epic Games\Launcher\Portal\Binaries\Win32\EpicGamesLauncher.exe

Gamecover7=Settings.png
Gamedir7=ms-settings:

Gamecover6=Valorant.png
Gamedir6=C:\Riot Games\Riot Client\RiotClientServices.exe

Gamecover5=TaskM.png
Gamedir5=C:\Windows\System32\taskmgr.exe

Gamecover4=AC3.png
Gamedir4=D:\GtaV\Assassins Creed III\AC3SP.exe

Gamecover3=Google Chrome.png
Gamedir3=C:\Program Files\Google\Chrome\Application\chrome.exe

Gamecover2=Discord.png
Gamedir2=C:\Users\Acer\AppData\Local\Discord\Update.exe

Gamecover29=Guitar Pro.png
Gamedir29=C:\Program Files (x86)\Arobas Music\Guitar Pro 7\GuitarPro7.exe

Gamecover28=Reaper.png
Gamedir28=C:\Program Files\REAPER (x64)\reaper.exe

Gamecover27=new.png

Gamecover26=Ableton LIVE.png
Gamedir26=C:\ProgramData\Ableton\Live 10 Suite\Program\Ableton Live 10 Suite.exe

Gamecover25=Figma.png
Gamedir25=C:\Users\Acer\AppData\Local\Figma\Figma.exe

Gamecover24=new.png

Gamecover23=Adobe Photoshop.png
Gamedir23=C:\Program Files\Adobe\Adobe Photoshop 2022\photoshop.exe

Gamecover22=iTunes.png
Gamedir22=C:\Program Files\WindowsApps\AppleInc.iTunes_12123.5.56009.0_x64__nzyj5cx40ttqa\iTunes.exe

Gamecover21=Adobe Premiere Pro.png
Gamedir21=C:\Program Files\Adobe\Adobe Premiere Pro 2022\Adobe Premiere Pro.exe

Gamecover20=Spotify.png
Gamedir20=C:\Users\Acer\AppData\Roaming\Spotify\Spotify.exe

Gamecover1=Files.png
Gamedir1=C:\Windows\explorer.exe

Gamecover9=new.png

Gamecover19=Adobe After Effects.png
Gamedir19=C:\Program Files\Adobe\Adobe After Effects 2022\Support Files\AfterFX.exe

Gamecover18=Netflix.png
Gamedir18=C:\Users\Acer\Desktop\Netflix

Gamecover17=Blender.png
Gamedir17=C:\Program Files\Blender Foundation\Blender 3.1\blender-launcher.exe

Gamecover16=Stremio.png
Gamedir16=C:\Users\Acer\AppData\Local\Programs\LNV\Stremio-4\stremio.exe

Gamecover15=new.png

Gamecover14=new.png

Gamecover13=Terminal.png
Gamedir13=C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.12.10983.0_x64__8wekyb3d8bbwe\wt.exe

Gamecover12=Epic Games.png
Gamedir12=C:\Program Files (x86)\Epic Games\Launcher\Portal\Binaries\Win32\EpicGamesLauncher.exe

Gamecover11=Microsoft Visual Studio Code.png
Gamedir11=C:\Users\Acer\AppData\Local\Programs\Microsoft VS Code\code.exe

Gamecover10=Steam.png
Gamedir10=C:\Program Files (x86)\Steam\steam.exe
