[Variables]
TotalGame=31

Gamecover1=Files.png
Gamedir1=C:\Windows\explorer.exe

Gamecover3=Google Chrome.png
Gamedir3=C:\Program Files\Google\Chrome\Application\chrome.exe

Gamecover5=TaskM.png
Gamedir5=C:\Windows\System32\taskmgr.exe

Gamecover7=Settings.png
Gamedir7=ms-settings:

Gamecover9=new.png

Gamecover11=Terminal.png
Gamedir11=C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.12.10983.0_x64__8wekyb3d8bbwe\wt.exe

Gamecover13=Microsoft Visual Studio Code.png
Gamedir13=C:\Users\Acer\AppData\Local\Programs\Microsoft VS Code\code.exe

Gamecover15=Slack.png
Gamedir15=C:\Users\Acer\AppData\Local\slack\slack.exe

Gamecover17=new.png

Gamecover19=Blender.png
Gamedir19=C:\Program Files\Blender Foundation\Blender 3.1\blender-launcher.exe

Gamecover21=Adobe After Effects.png
Gamedir21=C:\Program Files\Adobe\Adobe After Effects 2022\Support Files\AfterFX.exe

Gamecover23=Adobe Premiere Pro.png
Gamedir23=C:\Program Files\Adobe\Adobe Premiere Pro 2022\Adobe Premiere Pro.exe

Gamecover25=Adobe Photoshop.png
Gamedir25=C:\Program Files\Adobe\Adobe Photoshop 2022\photoshop.exe

Gamecover27=Figma.png
Gamedir27=C:\Users\Acer\AppData\Local\Figma\Figma.exe

Gamecover29=new.png

Gamecover31=Guitar Pro.png
Gamedir31=C:\Program Files (x86)\Arobas Music\Guitar Pro 7\GuitarPro7.exe





Gamecover16=new.png
Gamedir16=D:\Setup\x360ce.exe



Gamecover10=Valorant.png
Gamedir10=C:\Riot Games\Riot Client\RiotClientServices.exe

Gamecover8=God Of War
Gamedir8=D:\Games\God of War\GoW.exe

Gamecover6=AC3.png
Gamedir6=D:\GtaV\Assassins Creed III\AC3SP.exe

Gamecover4=Spiderman.png
Gamedir4=D:\Games\Spider-man Remastered\Spider-Man.exe


Gamecover2=Discord.png
Gamedir2=C:\Users\Acer\AppData\Local\Discord\Update.exe


Gamecover30=Reaper.png
Gamedir30=C:\Program Files\REAPER (x64)\reaper.exe


Gamecover28=Ableton LIVE.png
Gamedir28=C:\ProgramData\Ableton\Live 10 Suite\Program\Ableton Live 10 Suite.exe


Gamecover26=new.png


Gamecover24=iTunes.png
Gamedir24=C:\Program Files\WindowsApps\AppleInc.iTunes_12123.5.56009.0_x64__nzyj5cx40ttqa\iTunes.exe


Gamecover22=Spotify.png
Gamedir22=C:\Users\Acer\AppData\Roaming\Spotify\Spotify.exe




Gamecover20=Netflix.png
Gamedir20=C:\Users\Acer\Desktop\Netflix

Gamecover18=Stremio.png
Gamedir18=C:\Users\Acer\AppData\Local\Programs\LNV\Stremio-4\stremio.exe




Gamecover14=Epic Games.png
Gamedir14=C:\Program Files (x86)\Epic Games\Launcher\Portal\Binaries\Win32\EpicGamesLauncher.exe


Gamecover12=Steam.png
Gamedir12=C:\Program Files (x86)\Steam\steam.exe
