[Icon1]
Meter=Image
ImageName=#@#App\#Gamecover1#
LeftMouseUpAction=!Execute [!CommandMeasure Animate "interact(1)"][!CommandMeasure Animate "highlight(0)"][!CommandMeasure Animation "Stop 7"][!CommandMeasure Animation "Execute 7"]
MouseOverAction=[!CommandMeasure "Animate" "highlight(1)"][!CommandMeasure Animation "Stop 6"][!CommandMeasure Animation "Execute 6"]
MeterStyle=LayoutIcon

[DragNDropChild1]
Measure=Plugin
Plugin=Drag&Drop
Parent=DragNDropParent
Action=Path
DynamicVariables=1
OnEnterAction=[!SetVariable Edit 1]
Group=DropGroup
Bounds = Icon1
Disabled=1

[Icon2]
Meter=Image
ImageName=#@#App\#Gamecover2#
LeftMouseUpAction=!Execute [!CommandMeasure Animate "interact(2)"][!CommandMeasure Animate "highlight(0)"][!CommandMeasure Animation "Stop 7"][!CommandMeasure Animation "Execute 7"]
MouseOverAction=[!CommandMeasure "Animate" "highlight(2)"][!CommandMeasure Animation "Stop 6"][!CommandMeasure Animation "Execute 6"]
MeterStyle=LayoutIcon

[DragNDropChild2]
Measure=Plugin
Plugin=Drag&Drop
Parent=DragNDropParent
Action=Path
DynamicVariables=1
OnEnterAction=[!SetVariable Edit 2]
Group=DropGroup
Bounds = Icon2
Disabled=1

[Icon3]
Meter=Image
ImageName=#@#App\#Gamecover3#
LeftMouseUpAction=!Execute [!CommandMeasure Animate "interact(3)"][!CommandMeasure Animate "highlight(0)"][!CommandMeasure Animation "Stop 7"][!CommandMeasure Animation "Execute 7"]
MouseOverAction=[!CommandMeasure "Animate" "highlight(3)"][!CommandMeasure Animation "Stop 6"][!CommandMeasure Animation "Execute 6"]
MeterStyle=LayoutIcon

[DragNDropChild3]
Measure=Plugin
Plugin=Drag&Drop
Parent=DragNDropParent
Action=Path
DynamicVariables=1
OnEnterAction=[!SetVariable Edit 3]
Group=DropGroup
Bounds = Icon3
Disabled=1

[Icon4]
Meter=Image
ImageName=#@#App\#Gamecover4#
LeftMouseUpAction=!Execute [!CommandMeasure Animate "interact(4)"][!CommandMeasure Animate "highlight(0)"][!CommandMeasure Animation "Stop 7"][!CommandMeasure Animation "Execute 7"]
MouseOverAction=[!CommandMeasure "Animate" "highlight(4)"][!CommandMeasure Animation "Stop 6"][!CommandMeasure Animation "Execute 6"]
MeterStyle=LayoutIcon

[DragNDropChild4]
Measure=Plugin
Plugin=Drag&Drop
Parent=DragNDropParent
Action=Path
DynamicVariables=1
OnEnterAction=[!SetVariable Edit 4]
Group=DropGroup
Bounds = Icon4
Disabled=1

[Icon5]
Meter=Image
ImageName=#@#App\#Gamecover5#
LeftMouseUpAction=!Execute [!CommandMeasure Animate "interact(5)"][!CommandMeasure Animate "highlight(0)"][!CommandMeasure Animation "Stop 7"][!CommandMeasure Animation "Execute 7"]
MouseOverAction=[!CommandMeasure "Animate" "highlight(5)"][!CommandMeasure Animation "Stop 6"][!CommandMeasure Animation "Execute 6"]
MeterStyle=LayoutIcon

[DragNDropChild5]
Measure=Plugin
Plugin=Drag&Drop
Parent=DragNDropParent
Action=Path
DynamicVariables=1
OnEnterAction=[!SetVariable Edit 5]
Group=DropGroup
Bounds = Icon5
Disabled=1

[Icon6]
Meter=Image
ImageName=#@#App\#Gamecover6#
LeftMouseUpAction=!Execute [!CommandMeasure Animate "interact(6)"][!CommandMeasure Animate "highlight(0)"][!CommandMeasure Animation "Stop 7"][!CommandMeasure Animation "Execute 7"]
MouseOverAction=[!CommandMeasure "Animate" "highlight(6)"][!CommandMeasure Animation "Stop 6"][!CommandMeasure Animation "Execute 6"]
MeterStyle=LayoutIcon

[DragNDropChild6]
Measure=Plugin
Plugin=Drag&Drop
Parent=DragNDropParent
Action=Path
DynamicVariables=1
OnEnterAction=[!SetVariable Edit 6]
Group=DropGroup
Bounds = Icon6
Disabled=1

[Icon7]
Meter=Image
ImageName=#@#App\#Gamecover7#
LeftMouseUpAction=!Execute [!CommandMeasure Animate "interact(7)"][!CommandMeasure Animate "highlight(0)"][!CommandMeasure Animation "Stop 7"][!CommandMeasure Animation "Execute 7"]
MouseOverAction=[!CommandMeasure "Animate" "highlight(7)"][!CommandMeasure Animation "Stop 6"][!CommandMeasure Animation "Execute 6"]
MeterStyle=LayoutIcon

[DragNDropChild7]
Measure=Plugin
Plugin=Drag&Drop
Parent=DragNDropParent
Action=Path
DynamicVariables=1
OnEnterAction=[!SetVariable Edit 7]
Group=DropGroup
Bounds = Icon7
Disabled=1

[Icon8]
Meter=Image
ImageName=#@#App\#Gamecover8#
LeftMouseUpAction=!Execute [!CommandMeasure Animate "interact(8)"][!CommandMeasure Animate "highlight(0)"][!CommandMeasure Animation "Stop 7"][!CommandMeasure Animation "Execute 7"]
MouseOverAction=[!CommandMeasure "Animate" "highlight(8)"][!CommandMeasure Animation "Stop 6"][!CommandMeasure Animation "Execute 6"]
MeterStyle=LayoutIcon

[DragNDropChild8]
Measure=Plugin
Plugin=Drag&Drop
Parent=DragNDropParent
Action=Path
DynamicVariables=1
OnEnterAction=[!SetVariable Edit 8]
Group=DropGroup
Bounds = Icon8
Disabled=1

[Icon9]
Meter=Image
ImageName=#@#App\#Gamecover9#
LeftMouseUpAction=!Execute [!CommandMeasure Animate "interact(9)"][!CommandMeasure Animate "highlight(0)"][!CommandMeasure Animation "Stop 7"][!CommandMeasure Animation "Execute 7"]
MouseOverAction=[!CommandMeasure "Animate" "highlight(9)"][!CommandMeasure Animation "Stop 6"][!CommandMeasure Animation "Execute 6"]
MeterStyle=LayoutIcon

[DragNDropChild9]
Measure=Plugin
Plugin=Drag&Drop
Parent=DragNDropParent
Action=Path
DynamicVariables=1
OnEnterAction=[!SetVariable Edit 9]
Group=DropGroup
Bounds = Icon9
Disabled=1

[Icon10]
Meter=Image
ImageName=#@#App\#Gamecover10#
LeftMouseUpAction=!Execute [!CommandMeasure Animate "interact(10)"][!CommandMeasure Animate "highlight(0)"][!CommandMeasure Animation "Stop 7"][!CommandMeasure Animation "Execute 7"]
MouseOverAction=[!CommandMeasure "Animate" "highlight(10)"][!CommandMeasure Animation "Stop 6"][!CommandMeasure Animation "Execute 6"]
MeterStyle=LayoutIcon

[DragNDropChild10]
Measure=Plugin
Plugin=Drag&Drop
Parent=DragNDropParent
Action=Path
DynamicVariables=1
OnEnterAction=[!SetVariable Edit 10]
Group=DropGroup
Bounds = Icon10
Disabled=1

[Icon11]
Meter=Image
ImageName=#@#App\#Gamecover11#
LeftMouseUpAction=!Execute [!CommandMeasure Animate "interact(11)"][!CommandMeasure Animate "highlight(0)"][!CommandMeasure Animation "Stop 7"][!CommandMeasure Animation "Execute 7"]
MouseOverAction=[!CommandMeasure "Animate" "highlight(11)"][!CommandMeasure Animation "Stop 6"][!CommandMeasure Animation "Execute 6"]
MeterStyle=LayoutIcon

[DragNDropChild11]
Measure=Plugin
Plugin=Drag&Drop
Parent=DragNDropParent
Action=Path
DynamicVariables=1
OnEnterAction=[!SetVariable Edit 11]
Group=DropGroup
Bounds = Icon11
Disabled=1

[Icon12]
Meter=Image
ImageName=#@#App\#Gamecover12#
LeftMouseUpAction=!Execute [!CommandMeasure Animate "interact(12)"][!CommandMeasure Animate "highlight(0)"][!CommandMeasure Animation "Stop 7"][!CommandMeasure Animation "Execute 7"]
MouseOverAction=[!CommandMeasure "Animate" "highlight(12)"][!CommandMeasure Animation "Stop 6"][!CommandMeasure Animation "Execute 6"]
MeterStyle=LayoutIcon

[DragNDropChild12]
Measure=Plugin
Plugin=Drag&Drop
Parent=DragNDropParent
Action=Path
DynamicVariables=1
OnEnterAction=[!SetVariable Edit 12]
Group=DropGroup
Bounds = Icon12
Disabled=1

[Icon13]
Meter=Image
ImageName=#@#App\#Gamecover13#
LeftMouseUpAction=!Execute [!CommandMeasure Animate "interact(13)"][!CommandMeasure Animate "highlight(0)"][!CommandMeasure Animation "Stop 7"][!CommandMeasure Animation "Execute 7"]
MouseOverAction=[!CommandMeasure "Animate" "highlight(13)"][!CommandMeasure Animation "Stop 6"][!CommandMeasure Animation "Execute 6"]
MeterStyle=LayoutIcon

[DragNDropChild13]
Measure=Plugin
Plugin=Drag&Drop
Parent=DragNDropParent
Action=Path
DynamicVariables=1
OnEnterAction=[!SetVariable Edit 13]
Group=DropGroup
Bounds = Icon13
Disabled=1

[Icon14]
Meter=Image
ImageName=#@#App\#Gamecover14#
LeftMouseUpAction=!Execute [!CommandMeasure Animate "interact(14)"][!CommandMeasure Animate "highlight(0)"][!CommandMeasure Animation "Stop 7"][!CommandMeasure Animation "Execute 7"]
MouseOverAction=[!CommandMeasure "Animate" "highlight(14)"][!CommandMeasure Animation "Stop 6"][!CommandMeasure Animation "Execute 6"]
MeterStyle=LayoutIcon

[DragNDropChild14]
Measure=Plugin
Plugin=Drag&Drop
Parent=DragNDropParent
Action=Path
DynamicVariables=1
OnEnterAction=[!SetVariable Edit 14]
Group=DropGroup
Bounds = Icon14
Disabled=1

[Icon15]
Meter=Image
ImageName=#@#App\#Gamecover15#
LeftMouseUpAction=!Execute [!CommandMeasure Animate "interact(15)"][!CommandMeasure Animate "highlight(0)"][!CommandMeasure Animation "Stop 7"][!CommandMeasure Animation "Execute 7"]
MouseOverAction=[!CommandMeasure "Animate" "highlight(15)"][!CommandMeasure Animation "Stop 6"][!CommandMeasure Animation "Execute 6"]
MeterStyle=LayoutIcon

[DragNDropChild15]
Measure=Plugin
Plugin=Drag&Drop
Parent=DragNDropParent
Action=Path
DynamicVariables=1
OnEnterAction=[!SetVariable Edit 15]
Group=DropGroup
Bounds = Icon15
Disabled=1

[Icon16]
Meter=Image
ImageName=#@#App\#Gamecover16#
LeftMouseUpAction=!Execute [!CommandMeasure Animate "interact(16)"][!CommandMeasure Animate "highlight(0)"][!CommandMeasure Animation "Stop 7"][!CommandMeasure Animation "Execute 7"]
MouseOverAction=[!CommandMeasure "Animate" "highlight(16)"][!CommandMeasure Animation "Stop 6"][!CommandMeasure Animation "Execute 6"]
MeterStyle=LayoutIcon

[DragNDropChild16]
Measure=Plugin
Plugin=Drag&Drop
Parent=DragNDropParent
Action=Path
DynamicVariables=1
OnEnterAction=[!SetVariable Edit 16]
Group=DropGroup
Bounds = Icon16
Disabled=1

[Icon17]
Meter=Image
ImageName=#@#App\#Gamecover17#
LeftMouseUpAction=!Execute [!CommandMeasure Animate "interact(17)"][!CommandMeasure Animate "highlight(0)"][!CommandMeasure Animation "Stop 7"][!CommandMeasure Animation "Execute 7"]
MouseOverAction=[!CommandMeasure "Animate" "highlight(17)"][!CommandMeasure Animation "Stop 6"][!CommandMeasure Animation "Execute 6"]
MeterStyle=LayoutIcon

[DragNDropChild17]
Measure=Plugin
Plugin=Drag&Drop
Parent=DragNDropParent
Action=Path
DynamicVariables=1
OnEnterAction=[!SetVariable Edit 17]
Group=DropGroup
Bounds = Icon17
Disabled=1

[Icon18]
Meter=Image
ImageName=#@#App\#Gamecover18#
LeftMouseUpAction=!Execute [!CommandMeasure Animate "interact(18)"][!CommandMeasure Animate "highlight(0)"][!CommandMeasure Animation "Stop 7"][!CommandMeasure Animation "Execute 7"]
MouseOverAction=[!CommandMeasure "Animate" "highlight(18)"][!CommandMeasure Animation "Stop 6"][!CommandMeasure Animation "Execute 6"]
MeterStyle=LayoutIcon

[DragNDropChild18]
Measure=Plugin
Plugin=Drag&Drop
Parent=DragNDropParent
Action=Path
DynamicVariables=1
OnEnterAction=[!SetVariable Edit 18]
Group=DropGroup
Bounds = Icon18
Disabled=1

[Icon19]
Meter=Image
ImageName=#@#App\#Gamecover19#
LeftMouseUpAction=!Execute [!CommandMeasure Animate "interact(19)"][!CommandMeasure Animate "highlight(0)"][!CommandMeasure Animation "Stop 7"][!CommandMeasure Animation "Execute 7"]
MouseOverAction=[!CommandMeasure "Animate" "highlight(19)"][!CommandMeasure Animation "Stop 6"][!CommandMeasure Animation "Execute 6"]
MeterStyle=LayoutIcon

[DragNDropChild19]
Measure=Plugin
Plugin=Drag&Drop
Parent=DragNDropParent
Action=Path
DynamicVariables=1
OnEnterAction=[!SetVariable Edit 19]
Group=DropGroup
Bounds = Icon19
Disabled=1

[Icon20]
Meter=Image
ImageName=#@#App\#Gamecover20#
LeftMouseUpAction=!Execute [!CommandMeasure Animate "interact(20)"][!CommandMeasure Animate "highlight(0)"][!CommandMeasure Animation "Stop 7"][!CommandMeasure Animation "Execute 7"]
MouseOverAction=[!CommandMeasure "Animate" "highlight(20)"][!CommandMeasure Animation "Stop 6"][!CommandMeasure Animation "Execute 6"]
MeterStyle=LayoutIcon

[DragNDropChild20]
Measure=Plugin
Plugin=Drag&Drop
Parent=DragNDropParent
Action=Path
DynamicVariables=1
OnEnterAction=[!SetVariable Edit 20]
Group=DropGroup
Bounds = Icon20
Disabled=1

[Icon21]
Meter=Image
ImageName=#@#App\#Gamecover21#
LeftMouseUpAction=!Execute [!CommandMeasure Animate "interact(21)"][!CommandMeasure Animate "highlight(0)"][!CommandMeasure Animation "Stop 7"][!CommandMeasure Animation "Execute 7"]
MouseOverAction=[!CommandMeasure "Animate" "highlight(21)"][!CommandMeasure Animation "Stop 6"][!CommandMeasure Animation "Execute 6"]
MeterStyle=LayoutIcon

[DragNDropChild21]
Measure=Plugin
Plugin=Drag&Drop
Parent=DragNDropParent
Action=Path
DynamicVariables=1
OnEnterAction=[!SetVariable Edit 21]
Group=DropGroup
Bounds = Icon21
Disabled=1

[Icon22]
Meter=Image
ImageName=#@#App\#Gamecover22#
LeftMouseUpAction=!Execute [!CommandMeasure Animate "interact(22)"][!CommandMeasure Animate "highlight(0)"][!CommandMeasure Animation "Stop 7"][!CommandMeasure Animation "Execute 7"]
MouseOverAction=[!CommandMeasure "Animate" "highlight(22)"][!CommandMeasure Animation "Stop 6"][!CommandMeasure Animation "Execute 6"]
MeterStyle=LayoutIcon

[DragNDropChild22]
Measure=Plugin
Plugin=Drag&Drop
Parent=DragNDropParent
Action=Path
DynamicVariables=1
OnEnterAction=[!SetVariable Edit 22]
Group=DropGroup
Bounds = Icon22
Disabled=1

[Icon23]
Meter=Image
ImageName=#@#App\#Gamecover23#
LeftMouseUpAction=!Execute [!CommandMeasure Animate "interact(23)"][!CommandMeasure Animate "highlight(0)"][!CommandMeasure Animation "Stop 7"][!CommandMeasure Animation "Execute 7"]
MouseOverAction=[!CommandMeasure "Animate" "highlight(23)"][!CommandMeasure Animation "Stop 6"][!CommandMeasure Animation "Execute 6"]
MeterStyle=LayoutIcon

[DragNDropChild23]
Measure=Plugin
Plugin=Drag&Drop
Parent=DragNDropParent
Action=Path
DynamicVariables=1
OnEnterAction=[!SetVariable Edit 23]
Group=DropGroup
Bounds = Icon23
Disabled=1

[Icon24]
Meter=Image
ImageName=#@#App\#Gamecover24#
LeftMouseUpAction=!Execute [!CommandMeasure Animate "interact(24)"][!CommandMeasure Animate "highlight(0)"][!CommandMeasure Animation "Stop 7"][!CommandMeasure Animation "Execute 7"]
MouseOverAction=[!CommandMeasure "Animate" "highlight(24)"][!CommandMeasure Animation "Stop 6"][!CommandMeasure Animation "Execute 6"]
MeterStyle=LayoutIcon

[DragNDropChild24]
Measure=Plugin
Plugin=Drag&Drop
Parent=DragNDropParent
Action=Path
DynamicVariables=1
OnEnterAction=[!SetVariable Edit 24]
Group=DropGroup
Bounds = Icon24
Disabled=1

[Icon25]
Meter=Image
ImageName=#@#App\#Gamecover25#
LeftMouseUpAction=!Execute [!CommandMeasure Animate "interact(25)"][!CommandMeasure Animate "highlight(0)"][!CommandMeasure Animation "Stop 7"][!CommandMeasure Animation "Execute 7"]
MouseOverAction=[!CommandMeasure "Animate" "highlight(25)"][!CommandMeasure Animation "Stop 6"][!CommandMeasure Animation "Execute 6"]
MeterStyle=LayoutIcon

[DragNDropChild25]
Measure=Plugin
Plugin=Drag&Drop
Parent=DragNDropParent
Action=Path
DynamicVariables=1
OnEnterAction=[!SetVariable Edit 25]
Group=DropGroup
Bounds = Icon25
Disabled=1

[Icon26]
Meter=Image
ImageName=#@#App\#Gamecover26#
LeftMouseUpAction=!Execute [!CommandMeasure Animate "interact(26)"][!CommandMeasure Animate "highlight(0)"][!CommandMeasure Animation "Stop 7"][!CommandMeasure Animation "Execute 7"]
MouseOverAction=[!CommandMeasure "Animate" "highlight(26)"][!CommandMeasure Animation "Stop 6"][!CommandMeasure Animation "Execute 6"]
MeterStyle=LayoutIcon

[DragNDropChild26]
Measure=Plugin
Plugin=Drag&Drop
Parent=DragNDropParent
Action=Path
DynamicVariables=1
OnEnterAction=[!SetVariable Edit 26]
Group=DropGroup
Bounds = Icon26
Disabled=1

[Icon27]
Meter=Image
ImageName=#@#App\#Gamecover27#
LeftMouseUpAction=!Execute [!CommandMeasure Animate "interact(27)"][!CommandMeasure Animate "highlight(0)"][!CommandMeasure Animation "Stop 7"][!CommandMeasure Animation "Execute 7"]
MouseOverAction=[!CommandMeasure "Animate" "highlight(27)"][!CommandMeasure Animation "Stop 6"][!CommandMeasure Animation "Execute 6"]
MeterStyle=LayoutIcon

[DragNDropChild27]
Measure=Plugin
Plugin=Drag&Drop
Parent=DragNDropParent
Action=Path
DynamicVariables=1
OnEnterAction=[!SetVariable Edit 27]
Group=DropGroup
Bounds = Icon27
Disabled=1

[Icon28]
Meter=Image
ImageName=#@#App\#Gamecover28#
LeftMouseUpAction=!Execute [!CommandMeasure Animate "interact(28)"][!CommandMeasure Animate "highlight(0)"][!CommandMeasure Animation "Stop 7"][!CommandMeasure Animation "Execute 7"]
MouseOverAction=[!CommandMeasure "Animate" "highlight(28)"][!CommandMeasure Animation "Stop 6"][!CommandMeasure Animation "Execute 6"]
MeterStyle=LayoutIcon

[DragNDropChild28]
Measure=Plugin
Plugin=Drag&Drop
Parent=DragNDropParent
Action=Path
DynamicVariables=1
OnEnterAction=[!SetVariable Edit 28]
Group=DropGroup
Bounds = Icon28
Disabled=1

[Icon29]
Meter=Image
ImageName=#@#App\#Gamecover29#
LeftMouseUpAction=!Execute [!CommandMeasure Animate "interact(29)"][!CommandMeasure Animate "highlight(0)"][!CommandMeasure Animation "Stop 7"][!CommandMeasure Animation "Execute 7"]
MouseOverAction=[!CommandMeasure "Animate" "highlight(29)"][!CommandMeasure Animation "Stop 6"][!CommandMeasure Animation "Execute 6"]
MeterStyle=LayoutIcon

[DragNDropChild29]
Measure=Plugin
Plugin=Drag&Drop
Parent=DragNDropParent
Action=Path
DynamicVariables=1
OnEnterAction=[!SetVariable Edit 29]
Group=DropGroup
Bounds = Icon29
Disabled=1

[Icon30]
Meter=Image
ImageName=#@#App\#Gamecover30#
LeftMouseUpAction=!Execute [!CommandMeasure Animate "interact(30)"][!CommandMeasure Animate "highlight(0)"][!CommandMeasure Animation "Stop 7"][!CommandMeasure Animation "Execute 7"]
MouseOverAction=[!CommandMeasure "Animate" "highlight(30)"][!CommandMeasure Animation "Stop 6"][!CommandMeasure Animation "Execute 6"]
MeterStyle=LayoutIcon

[DragNDropChild30]
Measure=Plugin
Plugin=Drag&Drop
Parent=DragNDropParent
Action=Path
DynamicVariables=1
OnEnterAction=[!SetVariable Edit 30]
Group=DropGroup
Bounds = Icon30
Disabled=1

[Icon31]
Meter=Image
ImageName=#@#App\#Gamecover31#
LeftMouseUpAction=!Execute [!CommandMeasure Animate "interact(31)"][!CommandMeasure Animate "highlight(0)"][!CommandMeasure Animation "Stop 7"][!CommandMeasure Animation "Execute 7"]
MouseOverAction=[!CommandMeasure "Animate" "highlight(31)"][!CommandMeasure Animation "Stop 6"][!CommandMeasure Animation "Execute 6"]
MeterStyle=LayoutIcon

[DragNDropChild31]
Measure=Plugin
Plugin=Drag&Drop
Parent=DragNDropParent
Action=Path
DynamicVariables=1
OnEnterAction=[!SetVariable Edit 31]
Group=DropGroup
Bounds = Icon31
Disabled=1