[Variables]
width=52
height=52
;icon size

divider=4
;how slow animation calculation should be (increase to make animation longer)

step=50
;how many update to draw when interacted (increase for longer animation)

expand=2.5
;how big icon expand when highlighted (size multiplier)

padding=10
;increase to make icon smaller

autohide=0
; whether to hide icon

vertical=0
; vertical 0 for horizonal dock, 1 for vertical

direction=-1
; direction can be 1, 0 or -1
